language: php

php:
  - 7
  - hhvm
  - nightly

env:
  - BOOTSTRAP_ARGUMENT=yes  CONFIGURATION_ARGUMENT=yes  CONFIGURATION_FILE=yes
  - BOOTSTRAP_ARGUMENT=yes  CONFIGURATION_ARGUMENT=yes  CONFIGURATION_FILE=no
  - BOOTSTRAP_ARGUMENT=yes  CONFIGURATION_ARGUMENT=no   CONFIGURATION_FILE=yes
  - BOOTSTRAP_ARGUMENT=no   CONFIGURATION_ARGUMENT=yes  CONFIGURATION_FILE=yes
  - BOOTSTRAP_ARGUMENT=yes  CONFIGURATION_ARGUMENT=no   CONFIGURATION_FILE=no
  - BOOTSTRAP_ARGUMENT=no   CONFIGURATION_ARGUMENT=yes  CONFIGURATION_FILE=no
  - BOOTSTRAP_ARGUMENT=no   CONFIGURATION_ARGUMENT=no   CONFIGURATION_FILE=yes

matrix:
  allow_failures:
    - php: hhvm

sudo: false

before_script:
  - composer install --prefer-source
  - curl -OL test-flight.cundd.net/data/_Home.md

script:
  - >
    local arguments="";
    if [[ "$BOOTSTRAP_ARGUMENT" == "yes" ]]; then
      arguments="--bootstrap tests/resources/test-bootstrap.php $arguments";
    fi

    if [[ "$CONFIGURATION_ARGUMENT" == "yes" ]]; then
      arguments="--configuration tests/resources/test-configuration.json $arguments";
    fi

    if [[ "$CONFIGURATION_FILE" == "no" ]]; then
      rm .test-flight.json
    fi

    bin/test-flight $arguments;
    bin/test-flight $arguments src/;
    bin/test-flight $arguments _Home.md;

    bin/test-flight --list $arguments;
    bin/test-flight --list $arguments src/;
    bin/test-flight --list $arguments _Home.md;